name: Compile Spark Ldap Custom Auth
on:
  push:
    tags:
      - '**'

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

jobs:
  build:
    name: Build Spark Ldap Custom Auth
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'temurin'
          cache: 'maven'
      - name: Build Spark Ldap Auth ${{ steps.vars.outputs.tag }}
        run: |
          mvn clean compile package -DskipTests --no-transfer-progress -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d %H:%i:%s')"
      - name: Create release ${{ steps.vars.outputs.tag }}
        id: create-release
        uses: ncipollo/release-action@v1
        with:
          name: Spark Ldap Custom Auth ${{ steps.vars.outputs.tag }}
          artifacts: "target/*.jar"
          replacesArtifacts: true
          body: "Spark Ldap Custom Auth ${{ steps.vars.outputs.tag }} [Run timestamp ${{ steps.date.outputs.date }}]"
          allowUpdates: true
          tag: ${{ steps.vars.outputs.tag }}
          token: ${{ secrets.GITHUB_TOKEN }}